@startuml connecting

skinparam monochrome true
skinparam shadowing false
skinparam dpi 300
hide footbox

title Connecting two parties through HyperPath

actor alice as "Alice"
participant webapp_alice as "Alice's\nweb app"
participant hyperpath_alice as "Alice's\nHyperPath"
participant hyperpath_bob as "Bob's\nHyperPath"
participant webapp_bob as "Bob's\nweb app"
actor bob as "Bob"

alice -> webapp_alice: offer connection to Bob
activate webapp_alice

opt alice has no peer id yet
webapp_alice -> hyperpath_alice: create peer id
activate hyperpath_alice
hyperpath_alice --> webapp_alice: ""alice_id""
deactivate hyperpath_alice
end

webapp_alice -> hyperpath_alice: ""createChannel(alice_id, …)""
activate webapp_alice
activate hyperpath_alice
hyperpath_alice -> hyperpath_alice: create random\nchannel id
hyperpath_alice --> webapp_alice: channel with id
deactivate hyperpath_alice
deactivate webapp_alice
webapp_alice -> webapp_alice: show QR code\nwith channel id\nand ""alice_id""
webapp_alice -> hyperpath_alice: start channel
activate hyperpath_alice
activate webapp_alice
hyperpath_alice -> hyperpath_alice: handle ""/hyperpath/1.0.0""
note right: Alices's HyperPath is the listener

bob -> webapp_bob: open camera
activate webapp_bob
webapp_bob -> webapp_bob: scan QR code on\nAlice's screen
webapp_bob --> webapp_bob: QR code with\nchannel id\nand ""alice_id""
opt bob has no peer id yet
  webapp_bob -> hyperpath_bob: create peer id
  activate hyperpath_bob
  hyperpath_bob --> webapp_bob: ""bob_id""
  deactivate hyperpath_bob
end

webapp_bob -> hyperpath_bob: ""openChannel(bob_id, channel_id, key, alice_id)""
activate webapp_bob
activate hyperpath_bob
hyperpath_bob --> webapp_bob: channel
deactivate hyperpath_bob
deactivate webapp_bob
webapp_bob -> hyperpath_bob: ""connect()""
activate hyperpath_bob

activate webapp_bob
hyperpath_bob -> hyperpath_bob: ""dialProtocol(alice_id, /hyperpath/1.0.0)""
note left: Bob's HyperPath is the dialer

hyperpath_bob -// hyperpath_alice: send channel id over stream
activate hyperpath_alice
hyperpath_bob ---> webapp_bob: connected
deactivate webapp_bob
hyperpath_alice -> hyperpath_alice: verify channel id expected?
alt wrong channel id
  hyperpath_alice -> hyperpath_alice: close stream
  hyperpath_alice --> webapp_alice: report error???
else correct channel id
  hyperpath_alice -// hyperpath_bob: send identify msg over stream:\n"I am Alice [alice_id]"
  hyperpath_alice --> webapp_alice: connected
deactivate hyperpath_alice
end

deactivate webapp_alice

note over webapp_alice, webapp_bob
  Alice and Bob can now communicate over HyperPath
  using the API for sending and receiving messages.
end note

@enduml
