name: CI
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build and test
        run: |
          yarn
          ./devsetup.sh
          yarn build
          yarn test
          yarn test:prod
